### ISSUE TITLE
TinyTds silently crash when password text larger than 30 characters

### ISSUE THREAD

**Issue by tlttnz2018** [rails-sqlserver/tiny_tds#25]
When I use TinyTds::Client.new(:username=>'...', :password=>'....longer than 32 characters, actually 54 characters', :host=>"...') then it crash silently. When I reduced character to less or equal 30 characters then it works. Could you please fix it?

My environment: Ruby 1.9.2 on Windows.

**Comment by chadmyers** [comment]
@metaskills  What are your current thoughts on a 0.6.3 release? I'd like to get the >30 char password support and also get rid of this warning once and for all if I could.  Anything I can do to help? Thanks!

**Comment by metaskills** [comment]
@chadmyers I released v0.7.0 last month, it has what you need. :)

**Comment by chadmyers** [comment]
@metaskills Awesome! Thank you!  We were looking in the wrong place. We've already upgraded to 0.7.0 and no more warning.

**Comment by mastermaiknemo** [comment]
Hey there,

this problem still occurs during my development.
I use freeTDS version v0.91 and implemented the tiny tds gem like this : gem 'tiny_tds'.
Should I change to a specific version of tiny_tds to fix the "<30 Error"?

Best regards,

Michael

**Comment by mastermaiknemo** [comment]
Hi back again.

Sorry for spamming.

Solve it by following @wbond recommendations

Thanks! :+1:

**Comment by metaskills** [comment]
@mastermaiknemo I highly recommend using modern FreeTDS. See https://github.com/rails-sqlserver/tiny_tds#freetds-compatibility--configuration
